version: '3.4'

services:
  stackexchange:
    image: ${DOCKER_REGISTRY-}stackexchange
    build:
      context: .
      dockerfile: stackExchange/Dockerfile
    depends_on:
      - sqlserver
    environment:
      DB_HOST: sqlserver
      DB_NAME: StackExchangeDB
      DB_USER: StackExchangeUser
      DB_PASSWORD: StackExchangePassword

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd" 
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
